{{- if and .Values.nemoclaw.apiKey (not .Values.nemoclaw.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nemoclaw.fullname" . }}
  labels:
    {{- include "nemoclaw.labels" . | nindent 4 }}
type: Opaque
data:
  NVIDIA_API_KEY: {{ .Values.nemoclaw.apiKey | b64enc | quote }}
{{- end }}
